### ISSUE TITLE
AppContainer is not destroyed

### ISSUE THREAD

**Issue by rnowm** [magicismight/react-native-root-toast#101]
Hi, I have an issue with a toast appearing on top of my video player.
There's a youtube limitation on Android which makes the player pause when there's an overlay on top of it.
So even after the toast is dismissed, AppContainer is still there and the video cannot play.
Any Idea on how to fix that?
Thanks!
<img width="383" alt="Screenshot 2019-05-21 at 17 14 25" src="https://user-images.githubusercontent.com/1416057/58108637-7b248500-7bec-11e9-95c6-9baff7fdddd2.png">

**Comment by sunnylqm** [comment]
I dont get it. Can you post your code here?

**Comment by rnowm** [comment]
Sorry guys I just realized I was not closing the tost.
That as in the example, fixed the issue:
```
setTimeout(function () {
    Toast.hide(toast);
}, 500);
```
