### ISSUE TITLE
error in RN0.28

### ISSUE THREAD

**Issue by dioxide** [magicismight/react-native-root-toast#12]
the error is: "**Cannot read property 'visible' of undefined** ",  it doesn't work!

**Comment by beebase** [comment]
in /node_modules/react-native-root-toast/lib/toastContainer.js
build if around lines 139 and 163.
I haven't checked any side effects, but seems to work.

```
if (this._root)
      {
        this._root.setNativeProps({
                                    pointerEvents: '**auto**'
                                  }
        );
      } 
```
```
if (this._root)
      {
        this._root.setNativeProps({
                                    pointerEvents: '**none**'
                                  }
        );
      }
```

**Comment by acmeyer** [comment]
@dioxide I just created pr #17 to address this issue. Can get the fix also from my fork of the repo if this is no longer being maintained here: https://github.com/acmeyer/react-native-root-toast
