### ISSUE TITLE
【Usage】Is it necessary to call api like Toast.hide(this.toast)?

### ISSUE THREAD

**Issue by lchenfox** [magicismight/react-native-root-toast#128]
Thank you for contributing firstly. I have a question about `calling api` like `Toast.hide(toast)` after `let toast = Toast.show(...)`? That looks like a bit troublesome. I mean, can I directly call `Toast.show(...)` without `Toast.hide(toast)`?

Unfortunately, the memory is continuously speeding up when I press button many times to directly call `Toast.show(...)` without `Toast.hide(toast)`. Is there any other good ways or suggestions?

**Comment by sunnylqm** [comment]
Use a singleton module
```
let toast;
export function showToast(...) {
  toast  = Toast.show(...)
}
```

**Comment by lchenfox** [comment]
> Use a singleton module
> 
> ```
> let toast;
> export function showToast(...) {
>   toast  = Toast.show(...)
> }
> ```

Thanks a lot. It did solve my problem as what you said:

```
import Toast from "react-native-root-toast";

let toast;

export function showToast(msg, options) {
    toast && Toast.hide(toast);
    toast = Toast.show(msg, options);
}
```

And by the way. How do I add a mask for toast so any click events are disabled? I can't find any properties to show the mask. I guess many guys will like it. Related issue: Duplicate of #104

**Comment by sunnylqm** [comment]
It's not like a toast that I understand. You can implement it by using react-native-root-siblings, render a fullscreen transparent view before the toast.

**Comment by lchenfox** [comment]
Yeah. Maybe I'll have a try. 🤝
