### ISSUE TITLE
latest npm version is set to 3.3.1 which was published after 3.4.0

### ISSUE THREAD

**Issue by stefan-schweiger** [magicismight/react-native-root-toast#161]
Hi, currently on npm the latest version points to 3.3.1 eventhough there already exists a version 3.4.0. What is the reason for this?

**Comment by stefan-schweiger** [comment]
The last commit on this repo is from 6 month ago, which seems inline with version 3.4.0, what happened here? This somehow smells like a malicious takeover.

@sunnylqm @mmomtchev any idea what is going on here since you seem to be the most recent contributors?

Also pinging @magicismight even though he seems not to be really active in this project anymore.

**Comment by sunnylqm** [comment]
I guess ... it was a mistake and miscommunication between the maintainers. 
I suggest you install the lib directly from github

**Comment by stefan-schweiger** [comment]
Can this still be fixed somehow? just push a new 3.4.1 version maybe?

**Comment by sunnylqm** [comment]
done
