### ISSUE TITLE
请求支持iOS新的隐私政策(2024年5月1号将强制执行)

### ISSUE THREAD

**Issue by lxm1799** [magicismight/react-native-root-toast#176]
苹果官方要求SDK名单：https://developer.apple.com/cn/support/third-party-SDK-requirements/
苹果官方添加隐私api说明：https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc
因为当前是RN项目的toast，而且我看了下toast库iOS原生官方:https://github.com/scalessec/Toast
已经提供了隐私清单文件PrivacyInfo。
同时我看了下同类型RN库lottie-react-native，地址： https://github.com/lottie-react-native/lottie-react-native
也是添加了苹果新政策隐私清单的，所以希望也添加下，避免大范围影响iOS客户端上线工作，因为新政策在24年5月1号将强制执行

**Comment by sunnylqm** [comment]
本库并不包含任何原生代码，与隐私政策有何关系？

**Comment by lxm1799** [comment]
那应该没有问题，我以为此库这是通过引用原生第三方SDK实现

---- 回复的原邮件 ----
| 发件人 | Sunny ***@***.***> |
| 发送日期 | 2024年04月07日 18:12 |
| 收件人 | magicismight/react-native-root-toast ***@***.***> |
| 抄送人 | lxm1799 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [magicismight/react-native-root-toast] 请求支持iOS新的隐私政策(2024年5月1号将强制执行) (Issue #176) |

本库并不包含任何原生代码，与隐私政策有何关系？

**Comment by sunnylqm** [comment]
与原生toast毫无干系，甚至都不能称为sdk
