### ISSUE TITLE
Cannot read property 'setNativeProps' of null

### ISSUE THREAD

**Issue by Liqiankun** [magicismight/react-native-root-toast#39]
![111504235488_ pic](https://user-images.githubusercontent.com/11532418/29953908-5e86e8ae-8f06-11e7-958a-3fe9c96e71f1.jpg)
![2017-09-01 11 09 34](https://user-images.githubusercontent.com/11532418/29953911-61c4522c-8f06-11e7-91dd-7491b0ac4a88.png)
```
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-root-toast": "^1.3.0",
```

**Comment by Liqiankun** [comment]
@magicismight 给瞧瞧什么问题？谢谢

**Comment by Liqiankun** [comment]
#27 Fixed this issue!

**Comment by dkdaliyong** [comment]
still getting this error :(
    "react": "16.5.0",
    "expo": "^31.0.4",
    "react-native-root-toast": "^3.0.2"
it shows up when the component where <Toast /> is in is unmounted
