### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

### ISSUE THREAD

**Issue by Hemantsolanki103** [magicismight/react-native-root-toast#43]
Hi,
I installed "react-native-root-toast" and run the application. I got the error mentioned below:

ERROR: undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

I am newbie in React world. Please help me its appreciate me.

Thanks,

**Comment by linxiaoru** [comment]
i fixed it by changing the ToastContainer.js file
modified the
```javascript
static propTypes = {
        ...ViewPropTypes,
        containerStyle: ViewPropTypes.style,
...
```
to 
```javascript
static propTypes = {
        ...ViewPropTypes,
        containerStyle: View.propTypes.style,
...
```
because View.propTypes is deprecated and instead ViewPropTypes is used from RN44

**Comment by ymyqwe** [comment]
why there is no one made a pull request to this?

**Comment by magicismight** [comment]
Fixed in latest version.

**Comment by nhatnx** [comment]
Issue is still there in latest release.
