### ISSUE TITLE
root-toast depends on root-siblings, and root-siblings version is not compatible with React Native v0.48

### ISSUE THREAD

**Issue by KhalilKhalaf** [magicismight/react-native-root-toast#44]
So related to #41, but more english in it.

`root-toast` has a dependency: `root-siblings`

![screen shot 2017-09-08 at 3 53 55 pm](https://user-images.githubusercontent.com/14429474/30228946-effce084-94ad-11e7-88b0-c6f701ee7a56.png)

`root-siblings`' version is not compatible with any higher React Native versions (I am currently on 0.45 for this to work)

I need to upgrade RN so that other dependencies behave properly, but in order to do that, I will have to wipe out root-toast entirely.

**Comment by fuxianwei** [comment]
+1

**Comment by nfplay** [comment]
+1

**Comment by DavidKongDesheng** [comment]
+1

**Comment by baijunjie** [comment]
+1

**Comment by cbjs** [comment]
+1

**Comment by wbattel4607** [comment]
+2

**Comment by delia-m** [comment]
+1

**Comment by JoostVermeulen11** [comment]
+1

**Comment by t407289575** [comment]
@KhalilKhalaf 
had been fixed https://github.com/magicismight/react-native-root-siblings/pull/12

**Comment by alex-gunning** [comment]
+1

**Comment by EyalSi** [comment]
+1

**Comment by JingLiangWen** [comment]
+1

**Comment by magicismight** [comment]
This has been fixed in 2.2.0
