### ISSUE TITLE
_reactNative.AppRegistry.setWrapperComponentProvider is not a function

### ISSUE THREAD

**Issue by cheneywan** [magicismight/react-native-root-toast#53]
刚刚升级到 2.1.0 报这个错，rn 版本是 0.46.4

**Comment by wangsiyuan0215** [comment]
I got the same one! Anybody has any solution?

**Comment by wangsiyuan0215** [comment]
OK, I found the reason that why this error happened. Because the version 0.46.3 of React Native didn't have `setWrapperComponentProvider ` function, you can use 1.4.0 or upgrade you React Native to a 0.47.x upper.

**Comment by chapeljuice** [comment]
@wangsiyuan0215 looks like 1.2.1 doesn't exist, did you mean 1.1.2 or 1.2.0?

**Comment by magicismight** [comment]
For react-native <= 0.46 plz using 1.2.1.

**Comment by yutianhaijiao** [comment]
@magicismight   1.2.1 doesn't exist, did you mean 1.1.2 or 1.2.0?

**Comment by rouge3351** [comment]
if react-native version under 0.43.3, you should use react-native-root-toast version to 1.0.5 !
