### ISSUE TITLE
undefined is not a function(near '..._reactNative.AppRegistry.setWrapperComponentProvider...')

### ISSUE THREAD

**Issue by muyiyangyu** [magicismight/react-native-root-toast#60]
react-native@0.42.3,react-native-toast-toast@2.0.0 Report this error!At the same time, I want to know which version is used for 0.42.3?thank you!

**Comment by iversonwool** [comment]
I have the same issue.My react-native version is 0.42.1.

**Comment by afh19840516** [comment]
in react-native-root-siblings
change
import EventEmitter from 'react-native/Libraries/EventEmitter/EventEmitter';
to
import EventEmitter from 'react-native/Libraries/vendor/emitter/EventEmitter';

please exchange them

**Comment by iversonwool** [comment]
This repository Notice that： - react-native-root-toast >= 2.1.0 only supports react-native >= 0.47.0 , for react-native < 0.47.0 you can choose 2.0.0 or below.So I test below：I create two project with two react-native versions，one is 0.42.1， the other is 0.52.0. The version of 0.52.0 is OK，but the version of 0.42.1 occur this issue.

**Comment by yangxiang1994** [comment]
Yes, I switched the version to 1.1.2 and manually switched the react-native-root-siblings.Toast2.0.0 version of the sibling does not exist this file, I can only switch to the low version! @iversonwool @afh19840516

**Comment by akiradeveloper** [comment]
@yangxiang1994 What did you do precisely?
