### ISSUE TITLE
Toaster appears behind modals.

### ISSUE THREAD

**Issue by abrahampreciado** [magicismight/react-native-root-toast#64]
Toaster messages appear behind modals, there is no z-index functionality to move them into the front.

**Comment by jiyeon-dino** [comment]
how to solved?

**Comment by greedbell** [comment]
[react-native-top-modal](https://github.com/shimohq/react-native-top-modal) can solve this problem

**Comment by enagorny** [comment]
@greedbell Sorry could you clue how this react-native-root-toast could be applied here?
Should `react-native-root-toast` be using `react-native-root-toast`and PR should be created?

**Comment by Moseqi** [comment]
@abrahampreciado did you solved it?

**Comment by IsaacGluck** [comment]
Try `coverScreen={false}`
(If you're using [react-native-modal)](https://github.com/react-native-community/react-native-modal)

**Comment by thiagog3** [comment]
Same issue here.

**Comment by TranLuongTuanAnh** [comment]
@abrahampreciado did you solved it?

**Comment by sunnylqm** [comment]
If you are using root-toast v3.2+, you can do this do make it appear above modals
```
import { RootSiblingParent } from 'react-native-root-siblings;

// RootSiblingParent works like a mount point
<Modal>
<RootSiblingParent>
<YourContent />
</RootSiblingParent>
</Modal>
```

**Comment by TranLuongTuanAnh** [comment]
@sunnylqm Thanks for your solution

**Comment by viet97** [comment]
> If you are using root-toast v3.2+, you can do this to make it appear above modals
> 
> ```
> import { RootSiblingParent } from 'react-native-root-siblings;
> 
> // RootSiblingParent works like a mount point
> <Modal>
>   <RootSiblingParent>
>     <YourContent />
>   </RootSiblingParent>
> </Modal>
> ```

thank you so much
