### ISSUE TITLE
Module ‘react-native-root-toast’ does not exist in the Haste module map

### ISSUE THREAD

**Issue by 841660202** [magicismight/react-native-root-toast#71]
try many times , but only get this. i sure i can see the file in node_modules
<img width="337" alt="default" src="https://user-images.githubusercontent.com/18305361/39635944-75eece60-4ff1-11e8-81d2-79a45881b701.png">
![11](https://user-images.githubusercontent.com/18305361/39636226-2f6244e4-4ff2-11e8-85db-ec31434f0358.png)

**Comment by thientnc-ibl** [comment]
@841660202 
This error comes from this issue #75. Module `react-native-root-siblings` requires `react-redux`

**Comment by sunnylqm** [comment]
No. There is a little arrow icon on the top right corner, which means it is a symlink which is not supported by packager. You may have mistakenly executed `npm link` or some command like that to make these packages to be symlink.
