### ISSUE TITLE
Change toast width?

### ISSUE THREAD

**Issue by MrChristofferson** [magicismight/react-native-root-toast#72]
Thanks for this project!

Is there a way to modify the toast to take up the full width of the screen and not just the content?

**Comment by fumer79** [comment]
containerStyle: {
  backgroundColor: color.red,
  padding: 10,
  width: 240,
  height: 100,
},

**Comment by fumer79** [comment]
containerStyle: {
  padding: 10,
  width: 240,
  height: 100,
},

**Comment by kevando** [comment]
Thanks! For this effect I use the following


``` javascript

const toastParams = {
  delay: 200,
  position: (Platform.OS == 'ios' ? 64 : 54),
  shadow: false,
  opacity: 1.0,
  containerStyle: {
    paddingVertical: 1,
    width: sizes.width,
    borderRadius: 0,
  }
}
Toast.show(msg, {...toastParams, duration: 5000, backgroundColor: 'red'})
```

https://i.imgur.com/cBrXfTF.png
