### ISSUE TITLE
why it requires "react-native-root-siblings"?

### ISSUE THREAD

**Issue by xinyuwang** [magicismight/react-native-root-toast#75]
I like this pure javascript solution, however, why it requires "react-native-root-siblings"?
Furthermore, the "react-native-root-siblings" requires react-redux....
is this necessary?

**Comment by enthal** [comment]
Please at least discuss this in the README.  Thanks :)

**Comment by geminiyellow** [comment]
and `react-native-root-siblings` use `static-container`,
and 

```script
./node_modules/static-container/StaticContainer.js
Module parse failed: Unexpected token (5:9)
You may need an appropriate loader to handle this file type.
| 
| export default class extends Component {
|     props: {
|         shouldUpdate: boolean
|     };
```

i use `react-native-web`

**Comment by sunnylqm** [comment]
All root-xxx series components depend on root-siblings, which insert itself into the root level so everything can work like a root component.
