### ISSUE TITLE
react-native Modal covers toast message

### ISSUE THREAD

**Issue by Yandamuri** [magicismight/react-native-root-toast#83]
When ever Modal is opened toast message displays beneath the Modal window. A fix might make it right.

react-native version : 0.52.2
Platform: Android & IOS

**Expected behaviour**
   No matter how many Modal are opened, Toast must appear on top of all those Modals

**Observed Behaviour**
Toast is not appearing even if one Modal is opened.

**Comment by webbin** [comment]
Me Tooooooooo!

**Comment by SUpermin6u** [comment]
same problem at iOS

**Comment by geminiyellow** [comment]
+1

**Comment by sunnylqm** [comment]
react native modal is a native view, so impossible to be covered by a js component. Use root-modal instead.

**Comment by LiWeiQiangAndroid** [comment]
How Fix？

**Comment by DonaldGuo** [comment]
set lineHeight to options.textStyle, This is a bug in React Native Text Component, it's need set lineHeight for multiline text

```
Toast.show(message, {
    ...
    textStyle: {
        lineHeight:20
    },
});
```

**Comment by akhilsanker** [comment]
Hi,

Used `react-native-simple-toast`. It works fine
