### ISSUE TITLE
My Toast dont show!

### ISSUE THREAD

**Issue by herlan-evocorp** [magicismight/react-native-root-toast#87]
When I do call the toast api at the moment a modal is active the toast does not appear.

Any idea how to solve this?

**Comment by mtnptrsn** [comment]
I have the same problem.

**Comment by Gokaysim** [comment]
I had the same problem. 

My problem's cause was calling AppRegistry.setWrapperComponentProvider twice. Only last caller wraps the root component so toast does not work. Anyway probably you do not call even once but react-native-root-siblings( rnrs ) does. Normally rnrs prevents calling it twice but using two different rnrs packages is calls twice. Some packages (like react-native-dialog-manager) has its own node_modules folder so its own rnrs package. 

I could not find a solution to this. To prevent two rnrs, I have copied src of other libraries into my code.

**Comment by sunnylqm** [comment]
@herlan-evocorp A js component(toast) cannot go beyond a native component(modal)

**Comment by sunnylqm** [comment]
@Gokaysim 
Good point. I'll try to figure out a way to prevent this. For now you may try these:
1. Fork that repo and update its package.json and install your folk version instead
2. Use [yarn resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) to specify its dependency version.

**Comment by lehug** [comment]
conflict with "react-native-popup-dialog"

**Comment by sunnylqm** [comment]
@lehug What conflict?

**Comment by lehug** [comment]
> @lehug What conflict?

same as Gokaysim say.
when I both use this two, then react-native-root-toast not work.

**Comment by lehug** [comment]
@sunnylqm I try to user 3.0.2, then it works, thanks.
I see the different with 3.0.1 and 3.0.2, and found the only change is support "onPress" props, why this change fix this problem?

**Comment by sunnylqm** [comment]
@lehug Just cleanly reinstall 3.0.1 can also fix this issue. Cause the dependency is semantic version `^x.y.z`, which means it will always resolve to latest version under `x.`.

**Comment by sunnylqm** [comment]
@jasder Use the `latest` versions, which is `0.16.6` for `react-native-popup-dialog`.

**Comment by jasder** [comment]
@sunnylqm  
And In the version of react-native 0.56, calling api is not work, but the component call is no problem.
`"react-native": "0.56.0",`
`"react-native-root-toast": "^3.0.2"`

**Comment by weinixuehao** [comment]
It is still conflict to use both react-native-popup-dialog and this library

**Comment by lawrencewqy** [comment]
still conflict when i use react-native-popup-dialog

**Comment by sunnylqm** [comment]
Should be fixed in https://github.com/magicismight/react-native-root-siblings/commit/3aff9e68740f8359057297b103fbd48556b1addb . Please reinstall to see if it works.

**Comment by bosz** [comment]
> Should be fixed in [magicismight/react-native-root-siblings@3aff9e6](https://github.com/magicismight/react-native-root-siblings/commit/3aff9e68740f8359057297b103fbd48556b1addb) . Please reinstall (delete node_modules and npm/yarn lock files) to see if it works.

Wow, i gave up on this package in my last project cos using the api never worked. Just trying it now and it failed again. Used this suggestion; deleted node_modules file and installed it again . 

`rm -rf node_modules`
`npm install`

Works now like charm. Thanks for the heads up @sunnylqm

**Comment by zichil** [comment]
> @sunnylqm
> And In the version of react-native 0.56, calling api is not work, but the component call is no problem.
> `"react-native": "0.56.0",`
> `"react-native-root-toast": "^3.0.2"`

the same problem
