### ISSUE TITLE
ERROR: Unable to resolve "redux" from "node_modules/react-redux/lib/connect/mapDispatchToProps.js"

### ISSUE THREAD

**Issue by samuelpismel** [magicismight/react-native-root-toast#88]
After adding the `react-native-root-toast` in my project I got this error:
**Unable to resolve "redux" from "node_modules/react-redux/lib/connect/mapDispatchToProps.js"**

To solve this you can add explicitly the `redux` package in your project:

`yarn add redux` or `npm install redux`

**Comment by oreuuz** [comment]
hi, I want to know that  why must add redux ?

**Comment by shopshow** [comment]
why??

**Comment by iOSleep** [comment]
I did this to skip installing redux

1. Uninstall react-native-root-toast
npm uninstall --save react-native-root-toast

2. Install react-native-root-siblings@3.0.0 (probably without --save)
npm i react-native-root-siblings@3.0.0

3. Install react-native-root-toast
npm i --save react-native-root-toast

Once you do this - npm ls react-redux should return an empty list and npm ls react-native-root-siblings should be at version 3 under react-native-root-toast

**Comment by sunnylqm** [comment]
Fixed in https://github.com/magicismight/react-native-root-siblings/commit/13e3aab67cd738803f95bb2a82ffd1416c354530
