### ISSUE TITLE
Package incompatible with react-devtools - ERROR: Expected to find at least one React renderer.

### ISSUE THREAD

**Issue by samuelpismel** [magicismight/react-native-root-toast#89]
Unfortunately this package incompatible with `react-devtools` and when you toggle inspector and click on some element react throws the error: **Expected to find at least one React renderer.**

![image](https://user-images.githubusercontent.com/1752499/44935494-44010180-ad47-11e8-9af9-5d34d52f6866.png)

If you remove the package the error does not occur.

**Comment by samuelpismel** [comment]
Seems to be a problem with the `react-native-root-siblings` package.

**Comment by yasir-netlinks** [comment]
Hi guys, any solution for this problem ?

**Comment by samuelpismel** [comment]
Due to the lack of support and updates after months I have switched to another pure javascript cross platform library.

It's not hard to find, in fact is it really **easy** to find it and adapt it in your code.

**Comment by yasir-netlinks** [comment]
@samuelpismel  what Library did you go for ?

**Comment by sunnylqm** [comment]
Fixed in magicismight/react-native-root-siblings@30065fd

**Comment by yasir-netlinks** [comment]
@sunnylqm Hi there, so do we install react-native-root-siblings ? how to fix the issue!

**Comment by sunnylqm** [comment]
@yasir-netlinks just reinstall root-toast
