### ISSUE TITLE
Problems with both react-native-root-modal and react-native-root-toast

### ISSUE THREAD

**Issue by CoodeZhang** [magicismight/react-native-root-toast#97]
our project use both react-native-root-modal and react-native-root-toast, the first import component can't show

**Comment by iamsee** [comment]
same error

**Comment by sunnylqm** [comment]
Should be fixed in https://github.com/magicismight/react-native-root-siblings/commit/3aff9e68740f8359057297b103fbd48556b1addb . Please reinstall to see if it works.
